// Copyright 2012 Google Inc. All Rights Reserved.
//
// Grammar used for disambiguation of results and for confirming or
// canceling a call.

tag-semantics <literal>;

$root = /0.15/ $COMMAND | /0.85/ $OTHER;

$COMMAND = cancel {_cancel} | okay {_okay} | $DISAMBIG;

$DISAMBIG = select $digit;
$digit = $digit1 | $digit2 | $digit3;
$digit1 = 1 {_select_1};
$digit2 = 2 {_select_2};
$digit3 = 3 {_select_3};

$OTHER = ($OTHER_WORDS<1->) {_other};
$OTHER_WORDS =
        the |
        be |
        to |
        of |
        and |
        a |
        in |
        that |
        have |
        i |
        it |
        for |
        not |
        on |
        with |
        he |
        as |
        you |
        do |
        at |
        this |
        but |
        his |
        by |
        from |
        they |
        we |
        say |
        her |
        she |
        or |
        an |
        will |
        my |
        all |
        would |
        there |
        their |
        what |
        so |
        up |
        out |
        if |
        about |
        who |
        get |
        which |
        go |
        me |
        when |
        make |
        can |
        like |
        time |
        no |
        just |
        him |
        know |
        take |
        person |
        into |
        year |
        your |
        good |
        some |
        could |
        them |
        see |
        other |
        than |
        then |
        now |
        look |
        only |
        come |
        its |
        over |
        think |
        also |
        back |
        after |
        use |
        how |
        our |
        work |
        first |
        well |
        way |
        even |
        new |
        want |
        because |
        any |
        these |
        give |
        day |
        most |
        us
        ;
